### ISSUE TITLE
Demo.html should have nice menu bar - this issue is for first-pass version

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellioviz#103]
**Is your feature request related to a problem? Please describe.**
To use wellioviz as a GUI, it would be nice if there was a menu bar interface

**Describe the solution you'd like**
Menu bar brainstorm with picture is in this slidedeck towards the bottom: https://docs.google.com/presentation/d/1DPunsJgNrGR4Bk5FJrbbkoKMmRxOkhC6p_GN2BtRUX8/edit?usp=sharing

An initial working prototype spread throughout an Observable Notebook that has some of this functionality is this one: https://observablehq.com/@justingosses/hello-wellioviz-swap-out-log-no-other-changes-required-now-a

**Describe alternatives you've considered**
Some other type of condensed interface?

**Comment by dcslagel** [comment]
@JustinGOSSES , I'm interested to get this implemented.  I am scheduling myself to work on it next week : June 21 - 27.  If someone else gets to it before then that's great too.  :-)

DC

**Comment by JustinGOSSES** [comment]
I've started in on this a bit in this demo https://justingosses.github.io/wellioviz/demo_from_hackathon.html feel free to build on it or change the approach. 

It is currently being brought in from the ObservableHQ notebook pretty much one for one and could be a lot nicer.

**Comment by dcslagel** [comment]
Okay, Yep, `demo_from_hackathon.html` is a forward progression from what we did earlier.  I'll start with it and go from there.

**Comment by dcslagel** [comment]
@JustinGOSSES, 

UPDATE:  looking more closely at demo_from_hackathon.html,  its changes are introducing sliders, which is great!  However, I am not finding any menu specific changes there.  It looks like its menu is current with the current demo.html.  Am I overlooking something?

Regarding the sliders, are they at a point where they can be merged to demo.html?

Thanks,
DC

**Comment by JustinGOSSES** [comment]
Several of the sliders don't actually do anything yet. They exist, but they don't change anything when you move them. They do on the Observable notebook but not yet in demo_from_hackathon.html

**Comment by JustinGOSSES** [comment]
This has been cleared
