### ISSUE TITLE
Demo.html doesn't work, need to investigate

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellioviz#109]
**Describe the bug**

bundle.js:22171 Uncaught TypeError: Cannot read property 'split' of undefined
    at splitLineofType1 (bundle.js:22171)
    at las2json (bundle.js:22199)
    at convert_and_startHelpers (main.js:138)
    at HTMLButtonElement.onclick (demo.html:80)
splitLineofType1 @ bundle.js:22171
las2json @ bundle.js:22199
convert_and_startHelpers @ main.js:138
onclick @ demo.html:80
12main.js:76 Uncaught TypeError: $.ajax is not a function
    at readInLASFromASSETS (main.js:76)
    at HTMLButtonElement.onclick (demo.html:70)

**Comment by JustinGOSSES** [comment]
might relate to #103 or #102 ? @dcslagel

**Comment by dcslagel** [comment]
Is that error from running demo.html locally or from https://justingosses.github.io/wellioviz/demo.html?

Wonder if the bundle needs to be regenerated with the changes to demo.html for everything to work.  I'll give that a try locally.   I'll copy these changes in a demo-menu.html and post a new pull request.  That way we can check for 'online' issues before merging into the live demo.html.

DC

**Comment by JustinGOSSES** [comment]
I saw it when running:  https://justingosses.github.io/wellioviz/demo.html 

The bundle suggestion sounds plausible but haven't had chance to check.

**Comment by dcslagel** [comment]
I can see the issue when running demo.html locally and with the browsers dev-console open.  Okay the issue is caused by the by mistaken update of Jquery to Jquery-slim.  Fix is in #110.

**Comment by dcslagel** [comment]
https://github.com/JustinGOSSES/wellioviz/pull/110  fixes this and re-adds the new menu functionality.  Let me know if you would prefer these to be separate pull requests and I'll make that change.

The issue was that during the recent update of Bootstrap and its dependencies Jquery was updated to a 'slim' version that doesn't include ajax.

**Comment by JustinGOSSES** [comment]
Yep, merged in #110  and it is fixex

**Comment by dcslagel** [comment]
Great. :-)
