### ISSUE TITLE
USGS LAS logs from Houston area all seem to have a formatting 'error' that makes the trim function fail.

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellioviz#115]
**Describe the bug**
USGS LAS logs from Houston area all seem to have a formatting 'error' that makes the trim function fail in the demo app. Need to understand what is causing this and whether in wellio or wellioviz

**To Reproduce**
1. Go to https://webapps.usgs.gov/GeoLogLocator/#!/search 
2. Zoom in to Houston area. Select seemingly any well close to 610 north loop and download it to your local computer. 
3. Try to open it from local computer using the demo app: https://justingosses.github.io/wellioviz/demo.html 
4. When you press the "convert" button after loading the LAS file, it doesn't seem to convert. See error message in console about "trim" function can't be found, likely because object type is wrong or doesn't exist. 

**Expected behavior**
Message about conversion being successful and well appearing when you click "display" from menu options.

**Comment by dcslagel** [comment]
The fixes for this are in  
https://github.com/JustinGOSSES/wellio.js/pull/56

**Comment by JustinGOSSES** [comment]
Merged pull request and published to NPM as version 0.1.9. Also bumped the release to v0.1.9 on github.
