### ISSUE TITLE
Does it support realtime data streaming?

### ISSUE THREAD

**Issue by 40uf411** [JustinGOSSES/wellioviz#128]
I want to steam data and could only find this library. Does it support realtime data streaming?

**Comment by JustinGOSSES** [comment]
It consumes LAS files via wellio.js. You can also ingest JSON files and other data formats if you write an adapter for it.

LAS isn't a streaming data format where the data is broken into small chunks. Almost all well log file types aren't streaming data formats.

That being said......If you started with the LAS headers and then just added data to the existing file every second, you could make it work with data that was progressively streaming in.

**Comment by 40uf411** [comment]
Well, I am working with WITSML v2.0, which supports streaming. Once the problem of react compatibility is resolved I will test feeding it a stream of processed WITSML data. if it did not work, I ll try the way that you mention.

**Comment by JustinGOSSES** [comment]
The react problem is solved as noted in the other issue for it.

There’s various LAS to WITSML conversion tools out there from the looks of a quick google search, so you should be able to find a converter or create one based on those examples. Creating your own won’t be super easy but definitely possible.

**Comment by 40uf411** [comment]
Thank you. I appreciate your help.
