### ISSUE TITLE
Add optional depth curve name, depth title & depth units & depth type

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellioviz#27]
Add optional depth title & depth units. Currently not clear if depth is in md or TVD or ft. or meters.

Depth m. MD.

Depth - (DEPT) - feet - Total Vertical Depth
Depth Title - Depth Curve Name - depth units - depth type

**Comment by geopetoa** [comment]
Great work! 
A humble suggestion. 
Would be a nice addition to be able to display different depth types (MD, TVD, and/or TVDSS at the depth track at the same time.
