### ISSUE TITLE
allow for commas in number scales (ie 1,500 vs 1.500) 

### ISSUE THREAD

**Issue by kernant** [JustinGOSSES/wellioviz#52]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JustinGOSSES** [comment]
Comma's are already the default. It might have been changed in your code you're using with wellioviz?

If you go the recent observable notebook: https://observablehq.com/@justingosses/well-log-in-d3-js-v5-notebook-2
and go to part C and go to the function: takeInArraysAndGetObjectOfCurveDataForPlotting()
and put *10000 at the end of the line `newObj[CurveName] = arraysOfCurvesAndNames[0][CurveName][i]` like so : `newObj[CurveName] = arraysOfCurvesAndNames[0][CurveName][i]*10000`
you'll see the curve scale units in thousands using commas.
