### ISSUE TITLE
grey boxes returned with svg plot

### ISSUE THREAD

**Issue by kernant** [JustinGOSSES/wellioviz#54]
the boxes have id or class "svg_holder"

![image](https://user-images.githubusercontent.com/13925439/74169691-572d2780-4bf1-11ea-8c11-87f861dd3b4f.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JustinGOSSES** [comment]
Huh. If you use your browser's inspect tool, what does it tell you. Are those Divs? Do they have a class or ID?

**Comment by JustinGOSSES** [comment]
Do they each have that class or are they all in a div with that class?

**Comment by JustinGOSSES** [comment]
fixed this in last commit - https://github.com/JustinGOSSES/wellioviz/commit/21a09a3d39535d36e0d8766dd5064a87e979d620

- Forgot to clear a svg_holder div on rebuild inside CurveBox() function
- Had the same name for what is actually a curve_box_holder div , not the svg_holder div.

**Comment by JustinGOSSES** [comment]
Gray boxes shouldn't appear now. I added gray color on the Observable notebook for them and they aren't showing now.
