### ISSUE TITLE
add scale to header so it is visible in scroll

### ISSUE THREAD

**Issue by kernant** [JustinGOSSES/wellioviz#56]
![image](https://user-images.githubusercontent.com/13925439/74247534-d2ebaa80-4cab-11ea-9b5b-cf2b9e9fa3a1.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JustinGOSSES** [comment]
Have this sorta working locally. 

Adding axis to bottom of svg_header svg is easy. 

Getting it to appear with an appropriate number of ticks and in the right place no matter the number of curves or explicitly set size of header is taking more time.
