### ISSUE TITLE
testing in Edge shows library breaking

### ISSUE THREAD

**Issue by kernant** [JustinGOSSES/wellioviz#70]
syntax error with try catch statements
Please check in Edge

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JustinGOSSES** [comment]
Which version of Edge? @kernant 

I didn't find any general problem with try/catch & Edge from googling.

How would you rank this bug in terms or priority? 

I don't normally use a Windows machine, but I have an old 2006 laptop I can try to install Edge on.
