### ISSUE TITLE
Add new function

### ISSUE THREAD

**Issue by mehsan1** [JustinGOSSES/wellioviz#72]
can you please add below function in wellioviz as we are using this for our input object.

convertWellJSONToObjV2: function (depth, curve_data, UWI, CurveNames) {
      depth = depth[0];
      array_of_obj = []
      for (eachPt in depth) {
        obj = {}
        obj["UWI"] = UWI
        for (i in CurveNames) {
          obj[CurveNames[i]] = parseFloat(curve_data[CurveNames[i]][eachPt])
          obj["DEPTH"] = parseFloat(depth[eachPt])
        }
        array_of_obj.push(obj)
      }
      return array_of_obj
    }

**Comment by JustinGOSSES** [comment]
Added in commit https://github.com/JustinGOSSES/wellioviz/commit/c110fa7974bd64285fdaf170afc4835bae3338e3 & published as version 0.0.16

**Comment by JustinGOSSES** [comment]
Please check out the docs and make sure what I wrote is correct for how you intend to use that function. https://justingosses.github.io/wellioviz/#convertwelljsontoobjv2
