### ISSUE TITLE
Multi LogPlot enable users to show all plots at once and show 1 by 1

### ISSUE THREAD

**Issue by mehsan1** [JustinGOSSES/wellioviz#80]
currently it returns all plots visible. I have added a flag to toggle between these two 
1. Show all plots by default
2. Show the first and hide others and users can show/hide other plots , may be on click / event etc

Please view the picture attached for code difference

![image](https://user-images.githubusercontent.com/45680018/78493095-7f08b980-7762-11ea-8352-4babeaab42ec.png)

**Comment by JustinGOSSES** [comment]
pushed fix to master...will be included in version 0.0.21
