### ISSUE TITLE
Can't figure out how to order functions in the docs using documentation.js seems like it isn't an option based on issue reports from 2017!

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellioviz#94]
Can't figure out how to order functions in the docs using documentation.js seems like it isn't an option based on issue reports from 2017!

THIS IS Supper ANNOYING but most big JavaScript seems to be built on JSDoc which has same limitations.

**Comment by dcslagel** [comment]
Is lists of the current order and the desired order?

Are these the steps to duplicate the problem?

How to Make the Docs

- Add new markdown files to the docs by making changes to docs/doc_setup.yml or the documentation between /** **/ in the index.js file.
- Install locally documentation.js
- Run in the home directory of wellioviz:
  documentation build ./dist/index.js --config docs/doc_setup.yml -f html -o docs
- go to the docs directory. Run: python3 -m http.server Please note, that if you run the server   from anywhere except the docs directory, the image links won't work. The docs page on the github.com repository runs from the docs folder on the master branch as well.
- Go to a browser and open http://localhost:8000/index.html . You should see the docs.

Thanks,
DC

**Comment by JustinGOSSES** [comment]
Yes, those are the steps to replicate the problem. 

Under the header "Wellioviz Function Types", I'd like to insert specific functions under each time. So for example, I'd like to insert the documentation for the curvebox() function under the "plotting functions" header which is under "Wellioviz function types". 

The status quo is documentation.js puts the inline documentation for each function at the bottom of the docs in the order of the functions. 

From issues in documentation.js it looks like documentation.js might not be able to positive functions if they are treated as module exports, which all wellioviz functions are. However, that's my interpretation as that isn't spelled out exactly anywhere.

**Comment by JustinGOSSES** [comment]
Determined this is a limitation with documentation.js
